name: Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    name: exemple-build
    runs-on: ubuntu-20.04
    #container: python:3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "backend/requirements.txt"

      - name: Test
        run: python app/manage.py test app/
