name: exemple fonction
on:
  push:
    branches:
      - build_app

jobs:
  exemple-fonction:
    name: exemple fonction
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - name: Checkout code
        use: actions/checkout@v2

      - name: Setup Python 3.10.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "backend/requirements.txt"

      - name: fonctionnement docker
        run: docker-compose up --build

