name: Quality Assurance
on:
  push:
    branches: ['*']

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    steps:
      - name: Checkout code
        use: actions/checkout@v3

      - name: Setup Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "backend/requirements.txt"

      - name: fonctionnement docker
        run: docker-compose up --build

